# Generated by Django 5.0.3 on 2024-12-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/static/img', verbose_name='Imagen del producto'),
        ),
    ]
